name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build
      run: |
        xcodebuild clean build \
          -project WDBRemoveThreeAppLimit.xcodeproj \
          -scheme WDBRemoveThreeAppLimit \
          -configuration Release \
          -sdk iphoneos \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Create IPA
      run: |
        cd build/Release-iphoneos
        mkdir Payload
        cp -r WDBRemoveThreeAppLimit.app Payload/
        zip -r WDBRemoveThreeAppLimit.ipa Payload
          
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/Release-iphoneos/*.ipa
          build/Release-iphoneos/*.app
          build/Release-iphoneos/*.dylib
        retention-days: 7

    - name: Code Analysis
      run: |
        xcodebuild analyze \
          -project WDBRemoveThreeAppLimit.xcodeproj \
          -scheme WDBRemoveThreeAppLimit \
          -sdk iphoneos \
          CODE_SIGNING_ALLOWED=NO 