name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build
      run: |
        xcodebuild clean build \
          -project WDBRemoveThreeAppLimit.xcodeproj \
          -scheme WDBRemoveThreeAppLimit \
          -sdk iphoneos \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/
          *.ipa
          *.app
        retention-days: 7

    - name: Code Analysis
      run: |
        xcodebuild analyze \
          -project WDBRemoveThreeAppLimit.xcodeproj \
          -scheme WDBRemoveThreeAppLimit \
          -sdk iphoneos \
          CODE_SIGNING_ALLOWED=NO 